config/routes.rb
Rails.application.routes.draw do
  resources :accounts, only: [:new, :edit, :create, :update, :destroy]
  scope '/accounts' do
    # get '/', to: 'accounts#menu'
    get '/menu', to: 'accounts#menu', as: :menu
    get 'deposit', to: 'accounts#deposit', as: :deposit
    post 'deposit', to: 'accounts#make_deposit', as: :make_deposit
    get 'withdraw', to: 'accounts#withdraw', as: :withdraw
    post 'withdraw', to: 'accounts#make_withdraw', as: :make_withdraw
    get 'transfer', to: 'accounts#transfer', as: :transfer
    post 'transfer', to: 'accounts#make_transfer', as: :make_transfer
    get 'transactions', to: 'accounts#transactions', as: :transactions
  end

  get 'login', to: 'sessions#login', as: :login
  post 'login', to: 'sessions#create_session'
  get 'logout', to: 'sessions#logout', as: :logout
  get '/', to: 'sessions#login'
end

app/views/layouts/_admin-layout.html.erb
<%= render '/layouts/side-nav-bar'%>
<div class="main-content" id="panel">
    <%= render '/layouts/top-nav-bar'%>
    <%= render '/layouts/header'%>
    <div class="container-fluid mt--6">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <%= yield %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
    <div class="header bg-primary pb-6">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row align-items-center py-4">
                    <div class="col-6 col-xs-12">
                        <h6 class="h2 text-white d-inline-block mb-0"><%= (action_name != 'menu') ? action_name.capitalize : 'Account' %></h6>
                        <nav aria-label="breadcrumb" class="d-none d-md-inline-block ml-md-4">
                            <ol class="breadcrumb breadcrumb-links breadcrumb-dark">
                                <li class="breadcrumb-item">
                                    <%= link_to menu_url do %>
                                    <i class="fas fa-home"></i>
                                    <% end %>
                                </li>
                                <%if action_name != 'menu'%>
                                <li class="breadcrumb-item">
                                    <%= action_name.capitalize %>
                                </li>
                                <% end %>
                            </ol>
                        </nav>
                    </div>
                    <div class="col-6 col-xs-12">
                        <div class="card card-stats">
                            <!-- Card body -->
                            <div class="card-body">
                                <div class="row">
                                    <div class="col">
                                        <h5 class="card-title text-uppercase text-muted mb-0">
                                        <%= "Account Number: #{logged_account.account_number}"%>
                                        </h5>
                                        <h5 class="pt-2 card-title text-uppercase text-muted mb-0">Balance</h5>
                                        <span class="h2 font-weight-bold mb-0"> <%= number_to_currency(logged_account.money_amount) %> </span>
                                    </div>
                                    <div class="col-auto">
                                        <div class="icon icon-shape bg-gradient-red text-white rounded-circle shadow">
                                            <i class="ni ni-money-coins"></i>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

app/views/layouts/_side-nav-bar.html.erb
  <nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
      <!-- Brand -->
      <div class="sidenav-header  align-items-center">
        <a class="navbar-brand" href="javascript:void(0)">
          <%= image_tag  'nobe-logo.png', class: 'navbar-brand-img' %>
        </a>
      </div>
      <div class="navbar-inner">
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
          <!-- Nav items -->
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to(menu_url, class: 'nav-link') do %>
                <i class="ni ni-single-02 text-primary"></i>
                <span class="nav-link-text">Account Menu</span>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to(deposit_url, class: 'nav-link') do %>
                <i class="ni ni-fat-add text-primary"></i>
                <span class="nav-link-text">Deposit</span>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to(withdraw_url, class: 'nav-link') do %>
                <i class="ni ni-fat-delete text-primary"></i>
                <span class="nav-link-text">Withdraw</span>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to(transfer_url, class: 'nav-link') do %>
                <i class="ni ni-curved-next text-primary"></i>
                <span class="nav-link-text">Transfer</span>
              <% end %>
            </li>

            <li class="nav-item">
              <%= link_to(transactions_url, class: 'nav-link') do %>
                <i class="ni ni-curved-next text-primary"></i>
                <span class="nav-link-text">Transactions</span>
              <% end %>
            </li>
            
          </ul>
        </div>
      </div>
    </div>
  </nav>

app/views/layouts/_top-nav-bar.html.erb
    <!-- Topnav -->
    <nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <!-- Navbar links -->
          <ul class="navbar-nav align-items-center  ml-md-auto ">
            <li class="nav-item d-xl-none">
              <!-- Sidenav toggler -->
              <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
                <div class="sidenav-toggler-inner">
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                  <i class="sidenav-toggler-line"></i>
                </div>
              </div>
            </li>
          </ul>
          <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
            <li class="nav-item dropdown">
              <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <div class="media align-items-center">
                  <span class="avatar avatar-sm rounded-circle">
                    <i class="far fa-user-circle avatar rounded-circle" style="display: contents;"></i>
                  </span>
                  <div class="media-body  ml-2  d-none d-lg-block">
                    <span class="mb-0 text-sm  font-weight-bold"><%= logged_account.name %></span>
                  </div>
                </div>
              </a>
              <div class="dropdown-menu  dropdown-menu-right ">
                <div class="dropdown-header noti-title">
                  <h6 class="text-overflow m-0">Welcome!</h6>

                </div>
                <%= link_to(edit_account_path(0), class: 'dropdown-item') do %>
                  <i class="ni ni-single-02"></i>
                  <span>Edit Account</span>
                <% end %>
                <div class="dropdown-divider"></div>
                <%= link_to(logout_url, class: 'dropdown-item') do %>
                  <i class="ni  ni-user-run"></i>
                  <span>Logout</span>
                <% end %>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NOBE BANK</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body class="g-sidenav-hidden">
    <% if notice %>
      <p id="notice" style="display: none"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p id="alert" style="display: none"><%= alert %></p>
    <% end %>

    <% if logged_in? %>
      <%= render '/layouts/admin-layout'%>
    <% else %>
      <%= yield %>
    <% end %>
  </body>
</html>