config/routes.rb
Rails.application.routes.draw do
  resources :accounts, only: [:new, :edit, :create, :update, :destroy]
  scope '/accounts' do
    # get '/', to: 'accounts#menu'
    get '/menu', to: 'accounts#menu', as: :menu
    get 'deposit', to: 'accounts#deposit', as: :deposit
    post 'deposit', to: 'accounts#make_deposit', as: :make_deposit
    get 'withdraw', to: 'accounts#withdraw', as: :withdraw
    post 'withdraw', to: 'accounts#make_withdraw', as: :make_withdraw
    get 'transfer', to: 'accounts#transfer', as: :transfer
    post 'transfer', to: 'accounts#make_transfer', as: :make_transfer
    get 'transactions', to: 'accounts#transactions', as: :transactions
  end

  get 'login', to: 'sessions#login', as: :login
  post 'login', to: 'sessions#create_session'
  get 'logout', to: 'sessions#logout', as: :logout
  get '/', to: 'sessions#login'
end

app/models/account.rb
class Account < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { in: 3..50 }
  validates :email, presence: true, length: { maximum: 50 }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/, message: 'invalid email format'}
  validates :active, presence: true
  validates :account_number, presence: true, length: { is: 6 }, format: { with: /[0-9]{4}-[0-9]{1}/, message: 'account number format must be XXXX-X' }, uniqueness: true
  validates :password, presence: true, confirmation: true, on: :create, length: { in: 6..16 }
  validates :password_confirmation, presence: true, on: :create
  validates :money_amount, presence: true, numericality: { greater_than_or_equal_to: 0.0 }
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_action :set_account, only: %i[edit update destroy make_deposit make_withdraw make_transfer transactions generate_transaction]
  skip_before_action :require_login, only: %i[new create]
  before_action :set_transaction, only: [:deposit, :withdraw, :transfer]
  before_action :set_transaction_amount, only: %i[make_deposit make_withdraw make_transfer]
  before_action :check_password, only: %i[make_withdraw make_transfer]
  before_action :check_funds, only: %i[make_withdraw make_transfer]
  before_action :check_receiver, only: [:make_transfer]
  before_action :check_same_account, only: [:make_transfer]
  before_action :can_search, only: [:transactions]

  def menu; end

  def new
    redirect_to :menu if logged_in?
    @account = Account.new
  end

  def create
    @account = Account.new(account_params)
    @account.active = true
    if @account.save
      set_account_session(@account.id)
      redirect_to menu_url, notice: 'Account was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @account.update(update_params)
      redirect_to menu_url, notice: 'Account was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @account.update_attribute(:active, false)
    redirect_to logout_url
  end

  def deposit; end

  def make_deposit
    @account.money_amount += @transaction_amount
    if @account.save
      generate_transaction(:deposit, nil)
      redirect_to menu_url, notice: 'Deposit transaction success.'
    else
      redirect_to :deposit, alert: 'Deposit transaction fails.'
    end
  end

  def withdraw; end

  def make_withdraw
    @account.money_amount -= @transaction_amount
    if @account.save
      generate_transaction(:withdraw, nil)
      redirect_to menu_url, notice: 'Withdraw transaction success.'
    else
      redirect_to :withdraw, alert: 'Withdraw transaction fail.'
    end
  end

  def transfer; end

  def make_transfer
    @account.money_amount -= @transaction_amount + transfer_tax
    @receiver_account.money_amount += @transaction_amount
    if @account.save && @receiver_account.save
      generate_transaction(:incoming_transfer, @receiver_account)
      generate_transaction(:outgoing_transfer, nil)
      redirect_to menu_url, notice: 'Transfer transaction success.'
    else
      redirect_to :transfer, alert: 'Transfer transaction fail.'
    end
  end

  def transactions
    has_valid_dates = can_search
    start_date = has_valid_dates ? Time.parse(params.permit(:start_date)[:start_date] + ' 00:00:01') : nil
    end_date = has_valid_dates ? Time.parse(params.permit(:end_date)[:end_date] + ' 23:59:59') : nil
    @transactions_list = has_valid_dates ? AccountTransaction.where(account_id: @account.id, date: start_date..end_date) : AccountTransaction.where(account_id: @account.id)
  end

  private

  def set_account
    @account = logged_account
  end

  def set_transaction
    @transaction = Transaction.new
  end

  def action
    commit = params.permit(:commit)[:commit].downcase
  end
  def commit_redirect
    commit = action
    "/accounts/#{commit}"
  end

  def set_transaction_amount
    @transaction_amount = BigDecimal(transaction_params[:amount])
    rescue StandardError
      redirect_to commit_redirect, alert: 'Invalid amount.'
  end

  def account_params
    params.require(:account).permit(:name, :email, :account_number, :password, :password_confirmation)
  end

  def update_params
    params.require(:account).permit(:name, :email)
  end

  def transaction_params
    params[:transaction].permit(:amount, :account_number, :password, :start_date, :end_date, :commit)
  end

  def check_password
    unless @account.authenticate(transaction_params[:password])
      redirect_to commit_redirect, alert: 'Invalid password.'
    end
  end

  def check_receiver
    @receiver_account = Account.find_by(account_number: transaction_params[:account_number])
    redirect_to :transfer, alert: 'Invalid receiver account number.' if @receiver_account.nil?
  end

  def check_funds
    tax = (action == 'transfer') ? transfer_tax : 0
    redirect_to commit_redirect, alert: 'Not enough money.' unless @account.money_amount - @transaction_amount - tax >= 0.0
  end

  def check_same_account
    redirect_to commit_redirect, alert: 'Cannot transfer money to the same account.' unless @account.account_number != transaction_params[:account_number]
  end

  def transfer_tax
    now = DateTime.new
    tax = now.on_weekday? && now.hour >= 9 && now.hour <= 18 ? 5.0 : 7.0

    tax += @transaction_amount > 1000.0 ? 10.0 : 0.0

    tax
  end

  def generate_transaction(transaction_type, account)
    account = !account.nil? ? account : @account

    transaction = AccountTransaction.new(transaction_type: transaction_type)
    transaction.account_id = account.id
    transaction.date = Time.current
    transaction.transaction_value = transaction_type != :outgoing_transfer ? @transaction_amount : @transaction_amount + transfer_tax
    transaction.account_money_amount = account.money_amount
    transaction.save
  end

  def can_search
    is_valid_date = false
    return unless (params[:start_date].present? && params[:end_date].present?)
    is_valid_date = (Time.parse(params[:start_date]) rescue nil).present? && (Time.parse(params[:end_date]) rescue nil).present?
    if is_valid_date
      is_valid_date = Time.parse(params[:start_date]) < Time.parse(params[:end_date])
    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_with(model: account, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :account_number %>
    <%= form.text_field(:account_number, class: 'form-control', readonly: !(action_name == 'new' || action_name == 'create')) %>
    <%= content_tag(:div, account.errors[:account_number][0], class: 'invalid-feedback field_with_errors') if account.errors[:account_number]%>
  </div>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field(:name, class: 'form-control') %>
        <%= content_tag(:div, account.errors[:name][0], class: 'invalid-feedback field_with_errors') if account.errors[:name]%>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.email_field(:email, class: 'form-control')  %>
    <%= content_tag(:div, account.errors[:email][0], class: 'invalid-feedback field_with_errors') if account.errors[:email]%>
  </div>

  <% if action_name == 'new' || action_name == 'create' %>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field(:password, class: 'form-control') %>
      <%= content_tag(:div, account.errors[:password][0], class: 'invalid-feedback field_with_errors') if account.errors[:password]%>
    </div>

    <div class="form-group">
      <%= form.label :password_confirmation %>
      <%= form.password_field(:password_confirmation, class: 'form-control') %>
      <%= content_tag(:div, account.errors[:password_confirmation][0], class: 'invalid-feedback field_with_errors') if account.errors[:password_confirmation]%>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit(class: 'btn btn-primary btn-sm') %>
  </div>
<% end %>

app/views/accounts/_transaction-form.html.erb
<%= form_with(model: transaction, local: true, url: url_for(controller: 'accounts', action: action_name.downcase)) do |form| %>
  <% if action_name == 'transfer' %>
    <div class="form-group">
      <%= form.label :account_number %>
      <%= form.text_field(:account_number, class: 'form-control') %>
      <%= content_tag(:div, transaction.errors[:account_number][0], class: 'invalid-feedback field_with_errors') if transaction.errors[:account_number]%>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field(:amount, step: :any, class: 'form-control') %>
    <%= content_tag(:div, transaction.errors[:amount][0], class: 'invalid-feedback field_with_errors') if transaction.errors[:amount]%>
  </div>

  <% if action_name == 'transfer' || action_name == 'withdraw' %>
    <div class="form-group">
      <%= form.label :password %>
      <%= form.password_field(:password, class: 'form-control') %>
      <%= content_tag(:div, transaction.errors[:password][0], class: 'invalid-feedback field_with_errors') if transaction.errors[:password]%>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit(action_name.capitalize, class: 'btn btn-primary btn-sm') %>
  </div>
<% end %>

app/views/accounts/dashboard.html.erb
<p id="notice"><%= notice %></p>

<h1>Accounts</h1>

<h3>Account Dashboard</h3>

<br>

<%= link_to 'New Account', new_account_path %>

app/views/accounts/deposit.html.erb
<div class="m-7">
    <h1>Deposit</h1>

    <%= render 'transaction-form', transaction: @transaction %>
</div>

app/views/accounts/edit.html.erb
<div class="m-7">
    <h1>Update Account</h1>

    <%= render 'form', account: @account %>
</div>

app/views/accounts/menu.html.erb
<div class="row shortcuts px-4 py-7 justify-content-around">
<%= link_to(deposit_url, class: ' shortcut-item') do %>
    <span class="shortcut-media avatar rounded-circle bg-gradient-info">
        <i class="ni ni-fat-add"></i>
    </span>
    <small>Deposit</small>
<% end %>
<%= link_to(withdraw_url, class: ' shortcut-item') do %>
    <span class="shortcut-media avatar rounded-circle bg-gradient-green">
        <i class="ni ni-fat-delete"></i>
    </span>
    <small>Withdraw</small>
<% end %>
<%= link_to(transfer_url, class: ' shortcut-item') do %>
    <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
        <i class="ni ni-curved-next"></i>
    </span>
    <small>Transfer</small>
<% end %>
<%= link_to(transactions_url, class: ' shortcut-item') do %>
    <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
        <i class="ni ni-bullet-list-67"></i>
    </span>
    <small>Transactions</small>
<% end %>

app/views/accounts/new.html.erb
<div class="login-page">
    <div class="container-fluid pt-4">
        <h1>NOBE BANK</h1>
        <div class="card px-5 pb-5 pt-2" style="width: 60%;">
            <h3 class="text-center pb-3">New Account</h3>
                <%= render 'form', account: @account %>
        </div>
    </div>
</div>

app/views/accounts/transactions.html.erb
<div class="m-7">
  <h1>Account Transactions</h1>

  <%= form_tag transactions_path, method: :get, class: "form-inline my-3" do %>
    <div class="form-group mr-3">
      <%= label_tag :start_date, 'Start Date', class: 'mr-2' %>
      <%= date_field_tag 'start_date', params[:start_date], placeholder: "Start Date", class: "form-control" %>
    </div>
    <div class="form-group mx-2">
      <%= label_tag :end_date, 'End Date', class: 'mr-2' %>
      <%= date_field_tag 'end_date', params[:end_date], placeholder: "End Date", class: "form-control" %>
    </div>
          <%= submit_tag 'Filter', class: 'btn btn-primary btn-sm' %>
  <% end %>

  <table class="table align-items-center">
    <thead>
      <tr>
        <th>Date</th>
        <th>Transaction type</th>
        <th>Transaction value</th>
        <th>Account money amount</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transactions_list.each do |account_transaction| %>
        <tr>
          <td><%= account_transaction.date.strftime("%d/%m/%Y %H:%m")  %></td>
          <td><%= account_transaction.transaction_type.capitalize %></td>
          <td><%= number_to_currency(account_transaction.transaction_value) %></td>
          <td><%= number_to_currency(account_transaction.account_money_amount) %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/transfer.html.erb
<div class="m-7">
    <h1>Transfer</h1>

    <%= render 'transaction-form', transaction: @transaction %>
</div>

app/views/accounts/withdraw.html.erb
<div class="m-7">
    <h1>Withdraw</h1>

    <%= render 'transaction-form', transaction: @transaction %>
</div>